{
    "openapi": "3.0.0",
    "info": {
        "title": "Dictonary",
        "description": "API developed by Gabriel Sala to be used in the mobile backend integration. This is a challenge by Coodesh",
        "version": "1.0.0",
        "contact": {
            "email": "gabriel.sala.oliveira@gmail.com"
        }
    },
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create",
                "description": "Create a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "Gabriel Sala",
                                    "email": "gabriel.sala.oliveira@gmail.com",
                                    "password": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Update",
                "description": "Update user profile",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "required": false
                                    },
                                    "password": {
                                        "type": "string",
                                        "required": false
                                    },
                                    "old_password": {
                                        "type": "string",
                                        "required": false
                                    }
                                },
                                "example": {
                                    "name": "Gabriel Sala",
                                    "password": "123123",
                                    "old_password": "123123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Updated"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "User not found"
                    }
                }
            }
        },
        "/users/avatar": {
            "patch": {
                "tags": [
                    "User"
                ],
                "summary": "Upload",
                "description": "Update user profile picture",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "avatar": {
                                        "type": "string",
                                        "format": "base64"
                                    }
                                },
                                "example": {
                                    "avatar": "gabriel.png"
                                }
                            },
                            "encoding": {
                                "avatar": {
                                    "contentType": "image/png, image/jpeg"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Updated"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Not authorized"
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Sign In",
                "description": "User authentication",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email": "gabriel.sala.oliveira@gmail.com",
                                    "password": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Authenticated",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "id": 1,
                                        "name": "Gabriel Leal",
                                        "email": "gabriel.sala.oliveira@gmail.com",
                                        "avatar": "346dab6b457abadbbb2a-49030804.jpg",
                                        "created_at": "2022-08-22 19:59:46",
                                        "updated_at": "2022-08-22T20:07:45.340Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Not authorized/Invalid email or password"
                    }
                }
            }
        },
        "/sessions/refresh-token": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Refresh Token",
                "description": "Auth Refresh Token",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "token": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvZHJpZ29AZW1haWwuY29tIiwiaWF0IjoxNjYxMjc1NDAxLCJleHAiOjE2NjM4Njc0MDEsInN1YiI6IjEifQ.yQqqvmuZrF9ZM0LThzIu8dlwQtmuHdG0C_nwziXWyMo"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string",
                                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvZHJpZ29AZW1haWwuY29tIiwiaWF0IjoxNjYxMjc1NDE5LCJleHAiOjE2NjM4Njc0MTksInN1YiI6IjEifQ.kQoOrRyGvSkLcFS49ItDcLUEB7pEhbwyPRoEA5sR4ao"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Refresh token not found"
                    }
                }
            }
        },
        "/words/{id}": {
            "get": {
                "tags": [
                    "words"
                ],
                "summary": "Index",
                "description": "List all exercises",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": [
                                    {
                                        "id": 16,
                                        "word": "airport",
                                        "created_at": "2022-08-23 11:12:32"
                                    },
                                    {
                                        "id": 17,
                                        "word": "apple",
                                        "created_at": "2022-08-23 11:12:32"
                                    },
                                    {
                                        "id": 18,
                                        "word": "banana",
                                        "created_at": "2022-08-23 11:12:32"
                                    },
                                    {
                                        "id": 19,
                                        "word": "bicycle",
                                        "created_at": "2022-08-23 11:12:32"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/history/{id}": {
            "get": {
                "tags": [
                    "history"
                ],
                "summary": "Index",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "description": "List history by user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": [
                                    {
                                        "id": 1,
                                        "word": "airport",
                                        "user_id": 1,
                                        "created_at": "2022-08-23 11:55:29"
                                    },
                                    {
                                        "id": 2,
                                        "word": "apple",
                                        "user_id": 2,
                                        "created_at": "2022-08-23 11:55:29"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "post": {
                "tags": [
                    "history"
                ],
                "summary": "Index",
                "description": "Create user exercise history ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "exercise_id": {
                                        "type": "number"
                                    }
                                },
                                "example": [
                                    {
                                        "word": "airport",
                                        "user_id": 1,
                                        "created_at": "2022-08-23 11:55:29"
                                    },
                                    {
                                        "word": "apple",
                                        "user_id": 2,
                                        "created_at": "2022-08-23 11:55:29"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/favorite/{id}": {
            "get": {
                "tags": [
                    "favorite"
                ],
                "summary": "Index",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "description": "List history by user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": [
                                    {
                                        "word": "airport",
                                        "favorite": "Y",
                                        "updated_at": "2022-08-23 11:55:29"
                                    },
                                    {
                                        "word": "apple",
                                        "favorite": "N",
                                        "updated_at": "2022-08-23 11:55:29"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "post": {
                "tags": [
                    "favorite"
                ],
                "summary": "Index",
                "description": "Create user exercise history ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "exercise_id": {
                                        "type": "number"
                                    }
                                },
                                "example": [
                                    {
                                        "word": "airport",
                                        "favorite": "Y",
                                        "user_id": 1,
                                        "created_at": "2022-08-23 11:55:29"
                                    },
                                    {
                                        "word": "apple",
                                        "favorite": "Y",
                                        "user_id": 2,
                                        "created_at": "2022-08-23 11:55:29"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/dictionaryApi/{id}": {
            "get": {
                "tags": [
                    "dictionaryApi"
                ],
                "summary": "Index",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "description": "List history by user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": [
                                    {
                                      "word": "hello",
                                      "phonetic": "həˈləʊ",
                                      "phonetics": [
                                        {
                                          "text": "həˈləʊ",
                                          "audio": "//ssl.gstatic.com/dictionary/static/sounds/20200429/hello--_gb_1.mp3"
                                        },
                                        {
                                          "text": "hɛˈləʊ"
                                        }
                                      ],
                                      "origin": "early 19th century: variant of earlier hollo ; related to holla.",
                                      "meanings": [
                                        {
                                          "partOfSpeech": "exclamation",
                                          "definitions": [
                                            {
                                              "definition": "used as a greeting or to begin a phone conversation.",
                                              "example": "hello there, Katie!",
                                              "synonyms": [],
                                              "antonyms": []
                                            }
                                          ]
                                        },
                                        {
                                          "partOfSpeech": "noun",
                                          "definitions": [
                                            {
                                              "definition": "an utterance of ‘hello’; a greeting.",
                                              "example": "she was getting polite nods and hellos from people",
                                              "synonyms": [],
                                              "antonyms": []
                                            }
                                          ]
                                        },
                                        {
                                          "partOfSpeech": "verb",
                                          "definitions": [
                                            {
                                              "definition": "say or shout ‘hello’.",
                                              "example": "I pressed the phone button and helloed",
                                              "synonyms": [],
                                              "antonyms": []
                                            }
                                          ]
                                        }
                                      ]
                                    }
                                  ]
                                
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }   
        },
        "/files/${filename.png}": {
            "get": {
                "tags": [
                    "Image"
                ],
                "summary": "Show",
                "description": "Show image file",
                "parameters": [
                    {
                        "in": "path",
                        "name": "filename",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    }
}